[project]
name = "pipeline-project-alesiakarch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.9.0",
    "pytest>=8.3.5",
    "qtpy>=2.4.3",
    "tomlkit>=0.13.2",
    "usd-core>=25.5",
]
